service: crud-serverless-users

provider:
  name: aws
  runtime: nodejs20.x
  iam:
    role:
      statements:
        - Effect: Allow
          Action: "dynamodb:*"
          Resource: arn:aws:dynamodb:us-east-1:211125335109:table/usersTable
functions:
  get-users:
    package:
      patterns:
        - "getUsers/handler.js"
    handler: getUsers/handler.getUsers
    events:
      - http:
          path: users/{id}
          method: GET
  create-users:
    package:
      patterns:
        - "createUsers/handler.js"
    handler: createUsers/handler.createUsers
    events:
      - http:
          path: users
          method: POST
  update-users:
    package:
      patterns:
        - "updateUsers/handler.js"
    handler: updateUsers/handler.updateUsers
    events:
      - http:
          path: users/{id}
          method: PATCH
  delete-users:
    package:
      patterns:
        - "deleteUsers/handler.py"
    handler: deleteUsers/handler.deleteUsers
    runtime: python3.8
    events:
      - http:
          path: users/{id}
          method: DELETE

plugins:
  - serverless-offline
  - serverless-dynamodb
custom:
  dynamodb:
    # If you only want to use DynamoDB Local in some stages, declare them here
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      migrate: true

package:
  individually: true
  patterns:
    - "!*/**"

resources:
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: usersTable
        AttributeDefinitions:
          - AttributeName: pk
            AttributeType: S
        KeySchema:
          - AttributeName: pk
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
